import { ChomskyFont, crimsonFont, helveticaFont } from "@/lib/constants";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Wemeow Times",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${crimsonFont.className} ${helveticaFont.variable} ${ChomskyFont.variable} text-gray-900 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
